%{
/* 046266 Compilation Methods - Project Part 2
 * Flex lexer for C--.
 *
 * Produces tokens for the Bison parser and attaches a ParserNode* to yylval
 * for every returned token.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "part2.h"        /* defines YYSTYPE as ParserNode* */
#include "part2.tab.h"    /* token definitions (generated by bison) */

/* Helper: duplicate a quoted string token without the surrounding quotes */
static char* unquote_string(const char* text, int len)
{
    /* text includes the surrounding quotes. len is yyleng. */
    if (len < 2) {
        return strdup("");
    }
    int inner_len = len - 2;
    char* s = (char*)malloc((size_t)inner_len + 1);
    if (!s) {
        fprintf(stderr, "Failed malloc in unquote_string\n");
        exit(1);
    }
    memcpy(s, text + 1, (size_t)inner_len);
    s[inner_len] = '\0';
    return s;
}

%}

%option noyywrap
%option yylineno
%option noinput
%option nounput

/* ----------------------
 *  Regular definitions
 * ---------------------- */

id          [A-Za-z][A-Za-z0-9_]*
integernum  [0-9]+
realnum     [0-9]+"."[0-9]+
str         \"([^\"\\\r\n]|\\[tn'\"\\])*\"

relop       "=="|"<>"|"<="|">="|"<"|">"
addop       "+"|"-"
mulop       "*"|"/"

comment     "#"[^\n]*
whitespace  [ \t\r\n]+

%%

"int"       { yylval = makeNode("int",   NULL, NULL); return TK_INT; }
"float"     { yylval = makeNode("float", NULL, NULL); return TK_FLOAT; }
"void"      { yylval = makeNode("void",  NULL, NULL); return TK_VOID; }

"write"     { yylval = makeNode("write",  NULL, NULL); return TK_WRITE; }
"read"      { yylval = makeNode("read",   NULL, NULL); return TK_READ; }

"while"     { yylval = makeNode("while",  NULL, NULL); return TK_WHILE; }
"do"        { yylval = makeNode("do",     NULL, NULL); return TK_DO; }

"if"        { yylval = makeNode("if",     NULL, NULL); return TK_IF; }
"then"      { yylval = makeNode("then",   NULL, NULL); return TK_THEN; }
"else"      { yylval = makeNode("else",   NULL, NULL); return TK_ELSE; }

"return"    { yylval = makeNode("return", NULL, NULL); return TK_RETURN; }


"&&"        { yylval = makeNode("and",   yytext, NULL); return TK_AND; }
"||"        { yylval = makeNode("or",    yytext, NULL); return TK_OR; }
"!"         { yylval = makeNode("not",   yytext, NULL); return TK_NOT; }

{relop}     { yylval = makeNode("relop",  yytext, NULL); return TK_RELOP; }
{addop}     { yylval = makeNode("addop",  yytext, NULL); return TK_ADDOP; }
{mulop}     { yylval = makeNode("mulop",  yytext, NULL); return TK_MULOP; }
"="         { yylval = makeNode("assign", yytext, NULL); return TK_ASSIGN; }


{id}        { yylval = makeNode("id", yytext, NULL); return TK_ID; }


{realnum}    { yylval = makeNode("realnum", yytext, NULL); return TK_REALNUM; }
{integernum} { yylval = makeNode("integernum", yytext, NULL); return TK_INTEGERNUM; }

{str} {
    char* inner = unquote_string(yytext, yyleng);
    yylval = makeNode("str", inner, NULL);
    free(inner);
    return TK_STR;
}


"("|")"|"{"|"}"|","|";"|":" {
    yylval = makeNode(yytext, NULL, NULL);
    return yytext[0];
}


{comment}      { /* ignore comments */ }
{whitespace}   { /* ignore whitespace */ }


. {
    /* Any other single character is a lexical error */
    printf("Lexical error: '%s' in line number %d\n", yytext, yylineno);
    exit(1);
}

%%
